# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "897a00a477832a4d9cd548fa179ad0a8"
name = "banner-app"
application_url = "https://born-shaft-institutional-spectrum.trycloudflare.com"
embedded = true
handle = "banner-app-81"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://born-shaft-institutional-spectrum.trycloudflare.com/auth/callback", "https://born-shaft-institutional-spectrum.trycloudflare.com/auth/shopify/callback", "https://born-shaft-institutional-spectrum.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
